-- Create guides table for knowledge hub
CREATE TABLE IF NOT EXISTS "public"."guides" (
  "id" SERIAL PRIMARY KEY,
  "title" VARCHAR(255) NOT NULL,
  "slug" VARCHAR(255) NOT NULL UNIQUE,
  "description" TEXT NOT NULL,
  "content" TEXT NOT NULL,
  "category" VARCHAR(100) NOT NULL,
  "read_time" INTEGER NOT NULL DEFAULT 5,
  "image_url" VARCHAR(255),
  "featured" BOOLEAN DEFAULT FALSE,
  "author_name" VARCHAR(100),
  "author_image" VARCHAR(255),
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Add sample data
INSERT INTO "public"."guides" (title, slug, description, content, category, read_time, featured) VALUES
('Complete Guide to Study in USA', 'complete-guide-to-study-in-usa', 'Everything you need to know about applying to universities in the United States.', '# Complete Guide to Study in USA\n\nThis comprehensive guide covers everything from application requirements to student life in the United States.\n\n## Application Requirements\n\n- Common Application or Coalition Application\n- University-specific supplements\n- Standardized test scores (SAT/ACT)\n- English proficiency tests (TOEFL/IELTS)\n- Letters of recommendation\n- Transcript evaluation\n- Financial documentation\n\n## Timeline\n\n- Junior year: Research universities and take standardized tests\n- Summer before senior year: Begin applications\n- Fall of senior year: Submit applications (Early Decision/Action deadlines in November, Regular Decision in January)\n- Spring of senior year: Receive decisions and make final choice\n\n## Visa Process\n\n- Receive I-20 from your university\n- Pay SEVIS fee\n- Schedule visa interview\n- Prepare documents for F-1 student visa\n- Attend visa interview\n\n## Student Life\n\n- Housing options: on-campus dorms vs. off-campus apartments\n- Health insurance requirements\n- Campus resources and activities\n- Work opportunities with student visas\n\n## Financial Planning\n\n- Understanding the cost of attendance\n- Scholarship opportunities for international students\n- Banking in the USA\n- Creating a realistic budget', 'Country Guide', 15, TRUE),

('How to Write a Winning SOP', 'how-to-write-a-winning-sop', 'Tips and templates for crafting a statement of purpose that stands out to admissions committees.', '# How to Write a Winning Statement of Purpose\n\nYour Statement of Purpose (SOP) is one of the most critical components of your application. Here''s how to make it stand out.\n\n## Understanding the Purpose\n\nThe SOP is your opportunity to:\n- Demonstrate your academic and professional journey\n- Showcase your research interests and career goals\n- Explain why you''re a good fit for the specific program\n- Highlight what makes you unique as a candidate\n\n## Structure of a Strong SOP\n\n1. **Introduction**: Begin with a compelling hook that captures attention\n2. **Academic Background**: Highlight relevant coursework and projects\n3. **Professional Experience**: Discuss internships or jobs related to your field\n4. **Research Interests**: Clearly articulate your academic interests\n5. **Program Fit**: Explain why this specific program is right for you\n6. **Future Goals**: Connect the program to your career aspirations\n7. **Conclusion**: Summarize your strengths and restate your interest\n\n## Writing Tips\n\n- Be specific and use concrete examples\n- Avoid clichés and generic statements\n- Tailor each SOP to the specific program\n- Keep it concise (typically 1-2 pages)\n- Proofread carefully for grammar and spelling\n- Have others review your draft\n\n## Common Mistakes to Avoid\n\n- Writing a personal statement instead of a statement of purpose\n- Including irrelevant personal information\n- Being too general or vague\n- Repeating information from other parts of your application\n- Using overly flowery language', 'Application Tips', 10, TRUE),

('Scholarship Application Guide', 'scholarship-application-guide', 'Step-by-step process to find and apply for international scholarships.', '# Scholarship Application Guide\n\nNavigating the scholarship application process can be overwhelming. This guide breaks it down into manageable steps.\n\n## Types of Scholarships\n\n- **Merit-based**: Awarded based on academic, athletic, or artistic achievement\n- **Need-based**: Awarded based on financial need\n- **Country-specific**: For students from particular countries\n- **Subject-specific**: For students pursuing certain fields of study\n- **University-specific**: Offered directly by institutions\n- **Government-funded**: Sponsored by home or host country governments\n- **Private organizations**: Offered by companies, foundations, or nonprofits\n\n## Finding Scholarships\n\n1. University websites\n2. Government scholarship portals\n3. International organizations (Fulbright, Chevening, etc.)\n4. Scholarship search engines\n5. Professional associations in your field\n\n## Application Components\n\n- Application forms\n- Academic transcripts\n- Standardized test scores\n- Essays or personal statements\n- Letters of recommendation\n- Resume/CV\n- Financial documentation\n- Proof of language proficiency\n\n## Timeline Management\n\n- Start research 12-18 months before intended study date\n- Create a spreadsheet to track deadlines and requirements\n- Prepare standard documents in advance\n- Allow time for recommendation letters (4-6 weeks)\n- Submit applications well before deadlines\n\n## Writing Compelling Scholarship Essays\n\n- Address the prompt directly\n- Highlight achievements with specific examples\n- Demonstrate leadership and community involvement\n- Connect your goals to the scholarship''s mission\n- Be authentic and passionate', 'Scholarships', 12, TRUE),

('Student Visa Interview Tips', 'student-visa-interview-tips', 'Prepare for your visa interview with these expert tips and common questions.', '# Student Visa Interview Tips\n\nThe visa interview is a crucial step in your study abroad journey. Being well-prepared can significantly increase your chances of approval.\n\n## Before the Interview\n\n- **Know your program**: Be familiar with your course, university, and why you chose them\n- **Prepare documents**: Organize all required documents in a logical order\n- **Practice common questions**: Rehearse answers but don''t sound scripted\n- **Research the local embassy/consulate**: Know the specific procedures\n- **Plan your attire**: Dress professionally but comfortably\n\n## Required Documents\n\n- Valid passport\n- Visa application confirmation\n- Interview appointment letter\n- SEVIS fee receipt\n- I-20/CAS/Acceptance letter\n- Academic transcripts\n- Standardized test scores\n- Financial documents\n- Photographs\n\n## Common Interview Questions\n\n### About Your Studies\n- Why did you choose this university?\n- Why this specific program?\n- How does this program relate to your previous studies?\n- What are your future plans after graduation?\n\n### About Finances\n- How will you finance your education?\n- Who is your sponsor?\n- What is your family''s income?\n\n### About Ties to Home Country\n- What will you do after completing your studies?\n- Do you have family members in your home country?\n- Do you plan to return after graduation?\n\n## During the Interview\n\n- Arrive 30 minutes early\n- Speak clearly and confidently\n- Keep answers concise and relevant\n- Be honest - never lie or exaggerate\n- Maintain positive body language\n- Show strong ties to your home country', 'Visa', 8, FALSE),

('Budgeting for Study Abroad', 'budgeting-for-study-abroad', 'How to plan your finances and manage expenses while studying overseas.', '# Budgeting for Study Abroad\n\nFinancial planning is essential for a successful study abroad experience. This guide will help you prepare and manage your finances effectively.\n\n## Understanding the Full Cost\n\n### Upfront Costs\n- Application fees\n- Visa fees\n- Standardized test fees\n- Travel insurance\n- Airfare\n- Accommodation deposit\n- Initial settlement funds\n\n### Regular Expenses\n- Tuition and university fees\n- Accommodation\n- Utilities\n- Food and groceries\n- Transportation\n- Books and academic supplies\n- Phone and internet\n- Healthcare\n- Personal expenses\n- Emergency fund\n\n## Creating a Realistic Budget\n\n1. **Research living costs**: Use university estimates and student forums\n2. **Calculate monthly expenses**: Create a spreadsheet of all anticipated costs\n3. **Add buffer for unexpected expenses**: At least 10-15% extra\n4. **Monitor exchange rates**: Understand how currency fluctuations affect your budget\n5. **Track spending**: Use apps to monitor your expenses\n\n## Money Management Tips\n\n- Open a local bank account\n- Understand international transfer fees\n- Consider currency exchange strategies\n- Look for student discounts\n- Cook at home instead of eating out\n- Use public transportation\n- Buy used textbooks\n- Find on-campus employment if allowed\n\n## Financial Resources\n\n- Scholarships and grants\n- Family support\n- Personal savings\n- Part-time work (check visa restrictions)\n- Student loans\n\n## Managing Financial Stress\n\n- Create a realistic budget before departure\n- Review and adjust your budget regularly\n- Communicate openly with family about finances\n- Seek help from university financial advisors\n- Prioritize needs over wants', 'Financial Planning', 10, FALSE),

('Choosing the Right University', 'choosing-the-right-university', 'Factors to consider when selecting the perfect university for your academic goals.', '# Choosing the Right University\n\nSelecting the right university is a critical decision that will shape your academic journey and future career. Here are the key factors to consider.\n\n## Academic Factors\n\n### Program Quality\n- Global and national rankings in your field\n- Faculty expertise and research output\n- Curriculum structure and specialization options\n- Accreditation status\n- Class sizes and teaching methods\n- Research opportunities\n- Internship and practical experience options\n\n### Admission Requirements\n- Academic prerequisites\n- Standardized test scores needed\n- Language proficiency requirements\n- Application deadlines\n- Acceptance rates\n\n## Practical Considerations\n\n### Financial Aspects\n- Tuition fees and living expenses\n- Scholarship availability\n- Financial aid options\n- Return on investment for your field\n\n### Location\n- Country and city characteristics\n- Climate and environment\n- Safety considerations\n- Proximity to industry hubs in your field\n- Cost of living\n- Cultural fit and language barriers\n\n### Campus Life\n- Housing options and costs\n- Student organizations and activities\n- Support services for international students\n- Campus facilities (libraries, labs, sports)\n- Diversity and inclusion\n\n## Career Prospects\n\n- Graduate employment rates\n- Career services quality\n- Alumni network strength\n- Industry connections\n- Internship placement records\n- Post-graduation work visa options\n\n## Research Methods\n\n1. **University websites**: Official information about programs\n2. **Virtual tours**: Visual exploration of campus\n3. **Student forums**: Insights from current students\n4. **Education fairs**: Direct interaction with university representatives\n5. **Rankings**: Comparative data on institutions\n6. **Alumni interviews**: Perspectives on long-term value\n\n## Decision-Making Process\n\n1. Create a shortlist based on program quality and entry requirements\n2. Compare financial aspects and scholarship opportunities\n3. Evaluate location and lifestyle factors\n4. Assess career outcomes and employment prospects\n5. Consider personal fit and instinct', 'University Selection', 12, FALSE); 